apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid19-asp-net-deployment
  labels:
    app: covid19-asp-net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covid19-asp-net
  template:
    metadata:
      labels:
        app: covid19-asp-net
    spec:
      containers:
        - name: covid19-asp-net-be
          image: denisduev/covid19-asp-net-core:latest
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: covid19-service-asp-net
spec:
  selector:
    app: covid19-asp-net
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: https
      protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer
